### ISSUE TITLE
Is this local only?

### ISSUE THREAD

**Issue by TahaMindway** [Hibzz-Games/Hibzz.PackageEditor#2]
This made an awesome change on me. But is this working on local only? The package content changes on local but when i try to pull the changes on another pc, there are no changes avaliable nor on package repo.

**Comment by sliptrixx** [comment]
The package gets cloned to a subfolder in the `Documents/UnityPackageSource` folder and a symbolic link is created to the Unity Package folder. Since this folder is cloned using the git CLI, it's already git ready and the changes can be synced from this folder.

If you need any clarifications, please let me know 🙂
